package com.jerry.java.jvm.bridgemethod;

public class MyNode extends Node<Integer> {

    public MyNode(Integer data) { super(data); }

    public void setData(Integer data) {
        System.out.println("MyNode.setData");
        super.setData(data);
    }

    // Bridge method generated by the compiler
//    public void setData(Object data) {
//        setData((Integer) data);
//    }
}

// 用  javap -v MyNode  查看生成的字节码，会发现多了一个桥接的方法，该方法是由编译器自动生成的
//{
//public com.jerry.java.jvm.bridgemethod.MyNode(java.lang.Integer);
//        descriptor: (Ljava/lang/Integer;)V
//        flags: (0x0001) ACC_PUBLIC
//        Code:
//        stack=2, locals=2, args_size=2
//        0: aload_0
//        1: aload_1
//        2: invokespecial #1                  // Method com/jerry/java/jvm/bridgemethod/Node."<init>":(Ljava/lang/Object;)V
//        5: return
//        LineNumberTable:
//        line 5: 0
//        LocalVariableTable:
//        Start  Length  Slot  Name   Signature
//        0       6     0  this   Lcom/jerry/java/jvm/bridgemethod/MyNode;
//        0       6     1  data   Ljava/lang/Integer;
//
//public void setData(java.lang.Integer);
//        descriptor: (Ljava/lang/Integer;)V
//        flags: (0x0001) ACC_PUBLIC
//        Code:
//        stack=2, locals=2, args_size=2
//        0: getstatic     #2                  // Field java/lang/System.out:Ljava/io/PrintStream;
//        3: ldc           #3                  // String MyNode.setData
//        5: invokevirtual #4                  // Method java/io/PrintStream.println:(Ljava/lang/String;)V
//        8: aload_0
//        9: aload_1
//        10: invokespecial #5                  // Method com/jerry/java/jvm/bridgemethod/Node.setData:(Ljava/lang/Object;)V
//        13: return
//        LineNumberTable:
//        line 8: 0
//        line 9: 8
//        line 10: 13
//        LocalVariableTable:
//        Start  Length  Slot  Name   Signature
//        0      14     0  this   Lcom/jerry/java/jvm/bridgemethod/MyNode;
//        0      14     1  data   Ljava/lang/Integer;
//
//public void setData(java.lang.Object);  //编译器自动生成的桥接方法，源 java 文件中并没有定义这个方法
//        descriptor: (Ljava/lang/Object;)V
//        flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
//        Code:
//        stack=2, locals=2, args_size=2
//        0: aload_0
//        1: aload_1
//        2: checkcast     #6                  // class java/lang/Integer
//        5: invokevirtual #7                  // Method setData:(Ljava/lang/Integer;)V
//        8: return
//        LineNumberTable:
//        line 3: 0
//        LocalVariableTable:
//        Start  Length  Slot  Name   Signature
//        0       9     0  this   Lcom/jerry/java/jvm/bridgemethod/MyNode;
//}
