spring:
  datasource:
    url: jdbc:mysql://192.168.1.211:3306/zeus?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: testsql123
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test123
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 2 # 最小消息监听线程数
        max-concurrency: 2 # 最大消息监听线程数

